export const shortSparksList = [
	{
		name: 'Life Changing Advice',
		id: 'jim-rohn-life-changing-advice',
		src: '/assets/videos/motivation/jim-rohn/life-changing-advice.mp4',
		height: 350,
		previewImage: 'https://i.imgur.com/bS1Y4A9.png',
		description: 'Work harder on yourself ❤️',
	},
	{
		name: 'Why Not?',
		id: 'jim-rohn-why-not',
		src: '/assets/videos/motivation/jim-rohn/why-not.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/DlOd62I.png',
		description: 'Why not?',
	},
	{
		name: 'Man up',
		id: 'man-up',
		src: '/assets/videos/motivation/man-up.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/9u9MK5V.png',
		description: 'Man up!!!',
	},
	{
		name: 'You Are What You Think About',
		id: 'luke-belmar-you-are-what-you-think-about',
		src: '/assets/videos/motivation/luke-belmar/you-are-what-are-you-think-about.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/1rCkZWY.png',
		description: 'You are what you think about',
	},
	{
		name: 'Discipline for start & Consistency for finish',
		id: 'discipline-start-consistency-finish',
		src: '/assets/videos/motivation/discipline-start-consistency-finish.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/X5IBNTR.png',
		description: 'Discipline for start & Consistency for finish',
	},
	{
		name: `I'am unbeatable`,
		id: 'i-am-unbeatable',
		src: '/assets/videos/motivation/i-am-unbeatable.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/1MtydeA.png',
		description: `I'am unbeatable`,
	},
	{
		name: `In order to be successful`,
		id: 'in-order-to-be-successful',
		src: '/assets/videos/motivation/in-order-to-be-successful.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/7pKaYDv.png',
		description: 'In order to be successful',
	},
	{
		name: `Pain`,
		id: 'pain',
		src: '/assets/videos/motivation/pain.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/QHQPTVT.png',
		description: 'Pain',
	},
	{
		name: `The more you try the luckier you will be`,
		id: 'the-more-you-try-the-luckier-you-will-be',
		src: '/assets/videos/motivation/the-more-you-try-the-luckier-you-will-be.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/SG200Or.png',
		description: 'The more you try the luckier you will be ',
	},
	{
		name: 'brainwashed',
		id: 'brainwashed',
		src: '/assets/videos/motivation/robert-kiyosaki/brainwashed.mp4',
		height: 350,
		previewImage: 'https://i.imgur.com/WOqLqdI.png',
		description: '🧠🚿',
	},
	{
		name: 'make-mistakes-to-learn',
		id: 'make-mistakes-to-learn',
		src: '/assets/videos/motivation/robert-kiyosaki/make-mistakes-to-learn.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/pd0RjsC.png',
		description: 'You have to make mistakes to learn',
	},
	{
		name: 'save-money',
		id: 'save-money',
		src: '/assets/videos/motivation/robert-kiyosaki/save-money.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/nOzhDzC.png',
		description: 'Why would you save money?',
	},
]
