export const shortSparksList = [
	{
		name: 'Life Changing Advice',
		id: 'jim-rohn-life-changing-advice',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699034/life-changing-advice_wofrnn.mp4',
		height: 350,
		previewImage: 'https://i.imgur.com/bS1Y4A9.png',
		description: 'Work harder on yourself ❤️',
	},
	{
		name: 'Why Not?',
		id: 'jim-rohn-why-not',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699161/why-not_lrx5yf.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/DlOd62I.png',
		description: 'Why not?',
	},
	{
		name: 'You can do anything',
		id: 'you-can-do-anything',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1742654072/you-can-do-anything_uealig.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/tuXGxon.png',
		description: 'You can do anything',
	},
	{
		name: `what you are not changing you're choosing`,
		id: 'what-you-are-not-changing-you_re-choosing',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1741191413/what-you-are-not-changing-you_re-choosing_euagjy.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/jkMndX8.png',
		description: `what you are not changing you're choosing`,
	},
	{
		name: 'Life is a tragedy when seen in closeup, but a comedy in long-shot',
		id: 'life-is-a-tragedy-in-close-up-and-a-comedy-in-long-shot',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1741233734/life-is-a-tragedy-in-close-up-and-a-comedy-in-long-shot_j3jutu.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/SgTeskr.png',
		description: 'Life is a tragedy when seen in closeup, but a comedy in long-shot',
	},
	{
		name: 'Man up',
		id: 'man-up',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699016/man-up_kmsdys.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/9u9MK5V.png',
		description: 'Man up!!!',
	},
	{
		name: 'Where attention goes, energy flows',
		id: 'where-attention-goes-energy-flows',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1742270836/where-attention-goes-energy_flows_posrgp.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/UwRnY7w.png',
		description: 'Where attention goes, energy flows',
	},
	{
		name: 'Choose yourself',
		id: 'chooseyourself',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1742270838/choose-yourself_g1n2uk.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/rR8EoX2.png',
		description: 'Choose yourself',
	},
	{
		name: 'Ever tried, ever failed',
		id: 'ever-tried-ever-failed',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739698989/ever-tried-ever-failed_bvzzvy.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/9346IPr.png',
		description: 'Ever tried, ever failed',
	},
	{
		name: 'You Are What You Think About',
		id: 'luke-belmar-you-are-what-you-think-about',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699646/you-are-what-are-you-think-about_qfv9k4.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/1rCkZWY.png',
		description: 'You are what you think about',
	},
	{
		name: 'Discipline for start & Consistency for finish',
		id: 'discipline-start-consistency-finish',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739698987/discipline-start-consistency-finish_lmknup.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/X5IBNTR.png',
		description: 'Discipline for start & Consistency for finish',
	},
	{
		name: `I'am unbeatable`,
		id: 'i-am-unbeatable',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739698986/i-am-unbeatable_ougisd.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/1MtydeA.png',
		description: `I'am unbeatable`,
	},
	{
		name: `In order to be successful`,
		id: 'in-order-to-be-successful',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699000/in-order-to-be-successful_lb9yzc.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/7pKaYDv.png',
		description: 'In order to be successful',
	},
	{
		name: `Pain`,
		id: 'pain',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739698990/pain_y5fkw9.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/QHQPTVT.png',
		description: 'Pain',
	},
	{
		name: `The more you try the luckier you will be`,
		id: 'the-more-you-try-the-luckier-you-will-be',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739698991/the-more-you-try-the-luckier-you-will-be_ogtl5d.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/SG200Or.png',
		description: 'The more you try the luckier you will be ',
	},
	{
		name: 'brainwashed',
		id: 'brainwashed',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699660/brainwashed_k4yfsw.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/WOqLqdI.png',
		description: '🧠🚿',
	},
	{
		name: 'make-mistakes-to-learn',
		id: 'make-mistakes-to-learn',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699646/make-mistakes-to-learn_xcvuaw.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/pd0RjsC.png',
		description: 'You have to make mistakes to learn',
	},
	{
		name: 'save-money',
		id: 'save-money',
		src: 'https://res.cloudinary.com/hieu-buiminh/video/upload/v1739699673/save-money_lpnvtl.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/nOzhDzC.png',
		description: 'Why would you save money?',
	},
]
