export const shortSparksList = [
	{
		name: 'Life Changing Advice',
		id: 'jim-rohn-life-changing-advice',
		src: '/assets/videos/motivation/jim-rohn/life-changing-advice.mp4',
		height: 350,
		previewImage: 'https://i.imgur.com/bS1Y4A9.png',
		description: 'Work harder on yourself ❤️',
	},
	{
		name: 'Why Not?',
		id: 'jim-rohn-why-not',
		src: '/assets/videos/motivation/jim-rohn/why-not.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/DlOd62I.png',
		description: 'Why not?',
	},
	{
		name: 'You Are What You Think About',
		id: 'luke-belmar-you-are-what-you-think-about',
		src: '/assets/videos/motivation/luke-belmar/you-are-what-are-you-think-about.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/1rCkZWY.png',
		description: 'You are what you think about',
	},
	{
		name: 'brainwashed',
		id: 'brainwashed',
		src: '/assets/videos/motivation/robert-kiyosaki/brainwashed.mp4',
		height: 350,
		previewImage: 'https://i.imgur.com/WOqLqdI.png',
		description: '🧠🚿',
	},
	{
		name: 'make-mistakes-to-learn',
		id: 'make-mistakes-to-learn',
		src: '/assets/videos/motivation/robert-kiyosaki/make-mistakes-to-learn.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/pd0RjsC.png',
		description: 'You have to make mistakes to learn',
	},
	{
		name: 'save-money',
		id: 'save-money',
		src: '/assets/videos/motivation/robert-kiyosaki/save-money.mp4',
		height: 450,
		previewImage: 'https://i.imgur.com/nOzhDzC.png',
		description: 'Why would you save money?',
	},
]
